### Get the whole phonebook
GET http://localhost:3001/api/persons

### Get the summary
GET http://localhost:3001/info

### Get a person
GET http://localhost:3001/api/persons/1

### Get a ghost
GET http://localhost:3001/api/persons/1011

### Delete a person
DELETE http://localhost:3001/api/persons/1