### Get the whole phonebook
GET http://localhost:8080/api/persons

### Get the summary
GET http://localhost:8080/info

### Get a person
GET http://localhost:8080/api/persons/639b4109ab33aa6c65a5a9bd

### Get a ghost
GET http://localhost:8080/api/persons/1011

### Delete a person
DELETE http://localhost:8080/api/persons/1

### Add a person
POST http://localhost:8080/api/persons
content-type: application/json

{
    "name":"Sam",
    "number": "040-22334455",
    "animal": "cat"
}

### Add a person without sufficient content
POST http://localhost:8080/api/persons
content-type: application/json

{
    "name":"Wu",
    "animal": "cat"
}

### Unknown endpoint
post http://localhost:8080/api/unknown/pewpew

### Update a person
PUT http://localhost:8080/api/persons/639b98843f9d94bde1dc512a
content-type: application/json

{
    "name": "Amlie Grisly",
    "number": "246-9908"
}